spring.application.name=Retail-Q

server.port=9011
spring.datasource.url=jdbc:mysql://localhost:3306/retailiq?useSSL=false
spring.datasource.username=root
spring.datasource.password=rakki2024
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
 
# JPA and Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.shutdown.enabled=true
management.endpoint.env.show-values=ALWAYS
management.endpoint.configprops.show-values=ALWAYS
