package com.retailiq.entity;

public enum Role {
    STORE_ASSOCIATE,
    ECOMMERCE_MANAGER,
    INVENTORY_PLANNER,
    FULFILLMENT_MANAGER,
    CUSTOMER_SERVICE_AGENT,
    MARKETING_MANAGER,
    ADMIN
}